### ISSUE TITLE
crash on some files

### ISSUE THREAD

**Issue by mirlip** [mrossini-ethz/vector-render#1]
Hi Mrossini,
the vector render operator crashes on files I tested. Here is the traceback:
```
Traceback (most recent call last):
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 1120, in execute
    polytree.insert_poly(poly_obj)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 348, in insert_poly
    self.front_polys.insert_poly(fp)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 348, in insert_poly
    self.front_polys.insert_poly(fp)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 353, in insert_poly
    self.back_polys.insert_poly(bp)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 353, in insert_poly
    self.back_polys.insert_poly(bp)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 360, in insert_poly
    self.front_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 360, in insert_poly
    self.front_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 360, in insert_poly
    self.front_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 365, in insert_poly
    self.back_polys.insert_poly(poly)
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 345, in insert_poly
    split = poly.split(self.node_polys[0])
  File "C:\Blender\2.78\scripts\addons\vector-render.py", line 829, in split
    t2 = (-poly.pd - self.qq[s2 % self.N].dot(poly.nn)) / vt2.dot(poly.nn)
ZeroDivisionError: float division by zero

location: <unknown location>:-1
```

**Comment by mirlip** [comment]
It was with an orthogonal camera and option "create faces". All the rest was at default.

**Comment by mrossini-ethz** [comment]
Thanks for reporting. I will look into this when I find the time. How many polygons does your render have?

**Comment by mirlip** [comment]
in camera field of view not that much, but the whole scene is pretty big.

**Comment by mrossini-ethz** [comment]
I also had problems whenever if the scene was big.

You can click on the little buttons in the outliner to hide objects from the render. Can you render each individual object? Is the problem only occurring, if all (or too many objects) are rendered at once?

**Comment by mirlip** [comment]
sorry for the late reply, I somehow don't get notifications. In my case the problem is that the whole town in one object (imported and generated from OSM importer). There are to many buildings to separate by loose parts. It's a Blender limitation, it doesn't work well with high object count.
In the meantime, I create a pyramide following the FOV to do a boolean on the selected meshes, that is parented to camera to always cut everything that is outside the view also for big meshes. Maybe it would be possible to add this option to the addon?

**Comment by mrossini-ethz** [comment]
Does this mean that it works for you when the scene complexity is reduced? That is a clever idea with the pyramid parented to the camera and the boolean operation, well done! I am not sure though how to include this in the add-on.

**Comment by mirlip** [comment]
Yes, it works, at least in the cases I used it. Of course, complexity can be to high, even when restricting to the visible portion of the scene. 

For the pyramid I fine tuned it with a box actually, as it also works in orthogonal view and most of the time, reduce the geometry as good as the pyramid. 

If it's too complicated to code an adaptive size, another way would be to help user draw it by executing some macro (see link at the bottom) for him. 
The operator called by the macro (macro_name.define part in the link) could be:

1. Prepare:
- Go to camera view, 
- add a cube aligned to view (bpy.ops.mesh.primitive_cube_add(radius=1.0,  view_align=True)
- make it's draw type to wireframe

2. Position:
- ask the user to click in the middle of the camera to position the 3D Cursor.

3. draw:
- start the scale operator

4. finish:
- when user confirm with left click, scale it on it's z x 5000 to be sure to have everything and add a boolean to all meshes that were selected. If the cube is then deleted or named with the frame number could be an option as both make sens.

Some info on how to make a macro are here https://blender.stackexchange.com/questions/44971/how-to-use-bpy-ops-macro-defining-macro-steps
If you want to make it user friendly, NP station addon (availaible in contrib addons in buildbots https://builder.blender.org/download/) has some great macros and also some good functions to draw text in viewport to tell user what to do and with which key.
